django/mysite/lib/urls.py
# lib/urls.py

from django.urls import path
from . import views

app_name = 'lib'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('detail/', views.detail, name ='detail'),
    path('addBook/', views.addBook, name='addBook'),
    path('delBook/<int:book_id>', views.deleteBook, name='delBook'),
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('lib/', include('lib.urls')),
    path('admin/', admin.site.urls),
]

django/mysite/lib/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Author(models.Model):
    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=2)
    birth = models.DateTimeField('date birth')

django/mysite/lib/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from .models import Book


def index(request):
    return HttpResponse("Hello,world")


def detail(request):
    book_list = Book.objects.order_by('-pub_date')[:5]
    context = {}
    context['book_list'] = book_list
    context['section'] = "sitenews"
    return render(request, 'lib/detail.html', context)


def addBook(request):
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

    temp_book = Book(name = temp_name, author=temp_author, pub_house=temp_pub_house, pub_date = timezone.now())
    temp_book.save()

    return HttpResponseRedirect(reverse('lib:detail'))


def deleteBook(request, book_id):
    bookId = book_id
    Book.objects.filter(id=bookId).delete()
    return HttpResponseRedirect(reverse('lib:detail'))

django/mysite/lib/templates/base.html
<h1>Hello World!</h1>
<p>继承 Django 测试。</p>
{% block mainbody %}
    <p>original</p>
{% endblock %}

django/mysite/lib/templates/lib/detail.html
{% extends "base.html" %}

{% block mainbody %}
    <p>继承了 base.html 文件</p>
    {# 这是一个注释 #}
    <h1>Book List </h1>
    {% ifequal section 'sitenews' %}
        <h1>Site News</h1>
    {% else %}
        <h1>No News Here</h1>
    {% endifequal %}

    <table>
        <tr>
            <td>Book name</td>
            <td>author</td>
            <td>publisher</td>
            <td>publishdate</td>
            <td>corprator</td>
        </tr>
    {% for book in book_list.all %}
        <tr>
            <td>{{ book.name |lower}}</td>
            <td>{{ book.author }}</td>
            <td>{{ book.pub_house |upper}}</td>
            <td>{{ book.pub_date}}</td>
            <td> <a href ="{% url 'lib:delBook' book.id %}"> delete</a>
            </td>
        </tr>
    {% endfor %}
    </table>

    <form action="{% url 'lib:addBook' %}" method="post" name= "addBook">
        {% csrf_token %}
        <p> <span> book name :</span><input type="text" name="name"></p>
        <p> <span>author:</span> <input type="text" name="author"></p>
        <p> <span>publisher:</span> <input type="text" name="pub_house"></p>
         <input type="submit" value="add">
    <form>

{% endblock %}